services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/studiodb
      NEXTAUTH_SECRET: 88fc3d2d18b914a22517cf61b84a295bfce36047ff42a3e6335e649920a48f53
      NEXTAUTH_URL: http://localhost:3000 # Added NEXTAUTH_URL
      GOOGLE_AI_API_KEY: "AIzaSyCNeXIrPMYvfxA3FD8uHhMI9R1veKX7-kA" # Add your actual key
      AZURE_STORAGE_CONNECTION_STRING: "DefaultEndpointsProtocol=https;AccountName=societyplus;AccountKey=t3/QnVLIrsoyo+I+7/xJUK2p0riv4wPHJvA9lz1UoFnN2RgWQ3V5Pqd/JGWoCF6zm7JCHH3pDBdX+ASt7UuOcA==;EndpointSuffix=core.windows.net" # Add your actual connection string
      AZURE_STORAGE_CONTAINER_NAME: "media" # Add your actual container name
      # Ensure this matches your Next.js app's expectations for the database URL
      # Add other necessary environment variables for your app here
      # E.g., GOOGLE_API_KEY: ${GOOGLE_API_KEY} 
      # NEXT_PUBLIC_... variables should also be defined here if needed at runtime by the server
    volumes:
      # - .:/app # Mounts your current directory into the container for live code changes - Commented out for now
      - /app/node_modules # Excludes node_modules from being overwritten by the host mount (less relevant if .:/app is removed)
      - /app/.next # Excludes .next from being overwritten by the host mount (less relevant if .:/app is removed)
    # If you have a .env.local or .env file that your app uses for local development (outside Docker),
    # you might want to use it, but be careful with DATABASE_URL as it needs to point to the 'db' service.
    # env_file:
    #  - .env.local 

  db:
    image: postgres:15-alpine
    ports:
      - "5433:5432" # Exposing Postgres on host port 5433 to avoid conflict if local Postgres is running on 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: studiodb
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # You can also mount a SQL script to initialize the database on first run
      # - ./prisma/migrations:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  postgres_data:
